name: camera_app
description: A Camera App using CameraAwesome.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camerawesome:
    path: ../
  path_provider: ^2.0.11
  better_open_file: ^3.6.4
  google_mlkit_face_detection: ^0.5.0
  google_mlkit_barcode_scanning: ^0.5.0
  google_mlkit_text_recognition: ^0.5.0
  image: ^4.0.15
  rxdart: ^0.27.7
  video_player: ^2.5.0

dev_dependencies:
  exif: ^3.1.2
  flutter_test:
    sdk: flutter
  patrol: ^1.0.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

patrol:
  android:
    package_name: com.example.camera_app
  ios:
    bundle_id:
